In [1]:
from accelerate.utils import DistributedDataParallelKwargs

kwargs= DistributedDataParallelKwargs(find_unused_parameters=False)

In [2]:
print(kwargs)

DistributedDataParallelKwargs(dim=0, broadcast_buffers=True, bucket_cap_mb=25, find_unused_parameters=False, check_reduction=False, gradient_as_bucket_view=False, static_graph=False)


In [2]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]

c=zip(a,b)
for index,(m,n) in enumerate (c):
    print(index,(m,n))

0 (1, 6)
1 (2, 7)
2 (3, 8)
3 (4, 9)
4 (5, 10)


In [3]:
from diffusers.schedulers import DDIMScheduler

scheduler=DDIMScheduler()

print(scheduler.config.prediction_type)

epsilon


In [13]:
import  torch
a=torch.tensor([1,2,3,4,5])
b=torch.tensor([6,7,8,9,10])
c=torch.stack([a,b],dim=1)
print(c)
print(c.min(dim=1))

tensor([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]])
torch.return_types.min(
values=tensor([1, 2, 3, 4, 5]),
indices=tensor([0, 0, 0, 0, 0]))


In [5]:
b=a.min(dim=1)[0]
print(b)

torch.return_types.min(
values=tensor([-1.9812, -0.8370]),
indices=tensor([2, 2]))


In [6]:
import torch
tensor=torch.randint(0,100,(2,3,4)).float()
print(tensor)
tensor_avg=tensor.mean(dim=list(range(1,len(tensor.shape))))
print(tensor_avg)
tensor_repeat=tensor.repeat(2,3,6)
print(tensor_repeat)

tensor([[[35., 80., 95., 43.],
         [24., 50., 83., 40.],
         [71.,  8., 26., 58.]],

        [[94., 77., 91., 46.],
         [ 5., 46., 68., 74.],
         [36., 92., 58., 81.]]])
tensor([51.0833, 64.0000])
tensor([[[35., 80., 95., 43., 35., 80., 95., 43., 35., 80., 95., 43., 35., 80.,
          95., 43., 35., 80., 95., 43., 35., 80., 95., 43.],
         [24., 50., 83., 40., 24., 50., 83., 40., 24., 50., 83., 40., 24., 50.,
          83., 40., 24., 50., 83., 40., 24., 50., 83., 40.],
         [71.,  8., 26., 58., 71.,  8., 26., 58., 71.,  8., 26., 58., 71.,  8.,
          26., 58., 71.,  8., 26., 58., 71.,  8., 26., 58.],
         [35., 80., 95., 43., 35., 80., 95., 43., 35., 80., 95., 43., 35., 80.,
          95., 43., 35., 80., 95., 43., 35., 80., 95., 43.],
         [24., 50., 83., 40., 24., 50., 83., 40., 24., 50., 83., 40., 24., 50.,
          83., 40., 24., 50., 83., 40., 24., 50., 83., 40.],
         [71.,  8., 26., 58., 71.,  8., 26., 58., 71.,  8., 26., 58., 71.,  8.